version: '3'
services:
  maven:
    image: maven:3.8.3-openjdk-11-slim
    volumes:
      - .:/usr/src/mymaven
      - ./settings.xml:/root/.m2/settings-docker.xml
    working_dir: /usr/src/mymaven
    command: tail -f /dev/null
  openhab:
    image: "openhab/openhab:latest"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime/:/etc/localtime/:ro"
      - "./addons:/openhab/addons"
      - "./conf:/openhab/conf"
      - "./userdata:/openhab/userdata"
    environment:
      USER_ID: "1000"
      GROUP_ID: "1000"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Lisbon"